# Generated by Django 4.1.5 on 2023-07-10 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_teacher_detail_alter_course_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='qualification',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mobile_no',
        ),
    ]
