# Generated by Django 4.1.5 on 2023-07-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_studentcourseenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='enrolled_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
