# Generated by Django 4.1.5 on 2023-07-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_for',
            field=models.CharField(max_length=200, verbose_name='Notification For'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_text',
            field=models.TextField(verbose_name='Notification Text'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notifiread_status',
            field=models.BooleanField(default=False, verbose_name='Notification Status'),
        ),
    ]
