# Generated by Django 4.1.5 on 2023-07-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_quiz_alter_chapter_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestions',
            name='ans4',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='right_ans',
            field=models.TextField(),
        ),
    ]
